export type TipoAtividade =
  | 'CRIACAO'
  | 'COMENTARIO'
  | 'ALTERACAO_STATUS'
  | 'ALTERACAO_PRIORIDADE'
  | 'ATRIBUICAO_RESPONSAVEL';

export const TipoAtividade = {
  CRIACAO: 'CRIACAO' as TipoAtividade,
  COMENTARIO: 'COMENTARIO' as TipoAtividade,
  ALTERACAO_STATUS: 'ALTERACAO_STATUS' as TipoAtividade,
  ALTERACAO_PRIORIDADE: 'ALTERACAO_PRIORIDADE' as TipoAtividade,
  ATRIBUICAO_RESPONSAVEL: 'ATRIBUICAO_RESPONSAVEL' as TipoAtividade,
};
